"
----------------------------- RTIVITY -----------------------------------


  Rtivity is a software that analyses data generated by the activity monitors
developed by Trikinetics (https://trikinetics.com/)
1
  The code was developed by Rui Silva - REQUIMTE/UCIBIO, Dep. Drug Sciences, 
Faculty of Pharmacy, University of Porto

  This application can be run by the 'Run App' button present above and the
remaining codes of the application should be placed in the same folder as this
main code

"

### Install required packages before importing the libraries

#list of packages required
list.of.packages <- c("shiny","shinyFiles","shinyTime","shinyWidgets","behavr","data.table","ggplot2",
                      "damr","zeitgebr","sleepr","ggetho","DT","fs","dplyr","Hmisc","shinyjs","readr","colourpicker",
                      "lattice","survival","Formula","stringr","DescTools","graphics","doBy","zoo","tm","base",
                      "scales","shinythemes","xlsx",
                      "longitudinalData", "ActCR", "tools","nonlinearTseries","shinytitle")

#checking missing packages from list
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

#install missing ones
if(length(new.packages)) install.packages(new.packages, dependencies = TRUE)


library(shiny)
library(shinyFiles)
library(shinyTime)
library(shinyWidgets)
library(behavr)
library(data.table)
library(ggplot2)
library(damr) # input DAM data
library(zeitgebr) # periodogram computation
library(sleepr) # sleep analysis
library(ggetho) # behaviour visualisation
library(fs)
library(DT)
library(dplyr)
library(Hmisc)
library(shinyjs)
library(readr)
library(colourpicker)
library(lattice)
library(survival)
library(Formula)
library(stringr)
library(DescTools)
library(graphics)
library(doBy)
library(zoo)
library(tm)
library(base)
library(scales)
library(shinythemes)
library(xlsx)

library(longitudinalData) #Insert NAs
library(ActCR) #Circadian analysis
library(tools)
library(nonlinearTseries) #DFA
library(shinytitle)


shinyApp(
  
  
  ui <- navbarPage(id="pages",
                   theme = shinytheme("spacelab"),
                   
                   useShinyjs(),
  # Import and select data to analyse
                                    
                   tabPanel(title = "Data selection", 
                            
                            
    #                         tags$style("body {-moz-transform: scale(0.9, 0.9); /* Moz-browsers */
    # zoom: 0.9; /* Other non-webkit browsers */
    # zoom: 90%; /* Webkit browsers */}"),
                            use_shiny_title(),
                            busy_window_title("Running..."),

                      
                            tags$head(tags$style(".navbar {font-size:22px; font-weight:bold; font-family: Arial}
                                                 .nav-tabs {font-size:16px}")),

                              h1("Rtivity", align = "center", style = "font-family: Cambria; font-size: 70px;
                           font-weight:bold "),
                           #
                            h3("A versatile software for the automated analysis of animal activity and sleep patterns", align = "center", style = "font-family: Cambria; font-size: 35px;
                           font-weight:bold;margin-bottom: 80px"),
                            
                            
                            source("Data_selection_ui.R", local=TRUE)[1]
                   ),
                   
  # Represent activity and sleep in a time-continuous manner                
  
  tabPanel("Survival analysis",
           source("Survival_analysis_ui.R", local=TRUE)[1]),


    # Represent activity and sleep in a time-continuous manner

                  tabPanel("Visual inspection",
                          source("Visual_inspection_ui.R", local=TRUE)[1]),

  # Represent and calculate activity statistics

                  tabPanel("Activity analysis",
                           source("Activity_ui.R", local=TRUE)[1]
                  ),

  # Represent and calculate sleep statistics

                   tabPanel("Sleep analysis",
                            source("Sleep_ui.R", local=TRUE)[1]),

  # Represent and calculate circadian analysis

                  tabPanel("Rhythm and fractal analysis",
                           source("RhythmAndFractal_analysis_ui.R", local=TRUE)[1]
                  ),
),
  
  
  server <- function(input, output,session){
    
    ### Global functions ###
    
    #Delete conditions function
    
    # session$onSessionEnded(function() {
    #   stopApp()
    #   q("no")
    # })
    
    options(shiny.maxRequestSize=100*1024^2)
    
    change_window_title(
      session = shiny::getDefaultReactiveDomain(),
      title = "Rtivity",
      inactive_only = FALSE,
      revert_on_focus = inactive_only
    )
    

    deleteButtonColumn <- function(df, id, ...) {
      # function to create one action button as string
      f <- function(i) {
        as.character(
          actionButton(
            # The id prefix with index
            paste(id, i, sep="_"),
            label = NULL,
            icon = icon('trash'),
            onclick = 'Shiny.setInputValue(\"deletePressed\", this.id, {priority: "event"})'))
      }
      
      if(is.null(df)==FALSE){
        deleteCol <- unlist(lapply(seq_len(nrow(df)), f))
        
        data.frame(df,deleteCol)
      }
    }
    
    # Extract the number of the row to delete
    parseDeleteEvent <- function(idstr) {
      res <- as.integer(sub(".*_([0-9]+)", "\\1", idstr))
      if (! is.na(res)) res
    }
    
    #Set data
    source("Data_selection_server.R", local = TRUE)
    
    #Data integrity
    source("Data_integrity_server.R",local = TRUE)
    
    #### Graphs functions
    source("Graphs_aesthetics.R",local = TRUE)
    
    #Set data
    source("Survival_analysis_server.R", local = TRUE)

    #Time-continuous graphs
    source("Visual_inspection_server.R", local = TRUE)

    #Activity statistical graphs and parameters
    source("Activity_server.R", local = TRUE)

    #Sleep statistical graphs and parameters
    source("Sleep_server.R", local = TRUE)

    #Circadian nalysis
    source("RhythmAndFractal_analysis_server.R", local = TRUE)
  })

