"
----------------------------- RTIVITY -----------------------------------


  Rtivity is a software that analyses data generated by the activity monitors
developed by Trikinetics (https://trikinetics.com/)

  The code was developed by Rui Silva - REQUIMTE/UCIBIO, Dep. Drug Sciences, 
Faculty of Pharmacy, University of Porto

  This application can be run by the 'Run App' button present above and the
remaining codes of the application should be placed in the same folder as this
main code

"

### Install required packages before importing the libraries

#list of packages required
list.of.packages <- c("shiny","shinyFiles","shinyTime","shinyWidgets","behavr","data.table","ggplot2",
                      "damr","zeitgebr","sleepr","ggetho","DT","fs","dplyr","Hmisc","shinyjs","readr","colourpicker",
                      "lattice","survival","Formula","stringr","DescTools","graphics","doBy","zoo","tm","base",
                      "scales","shinythemes","xlsx")

#checking missing packages from list
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

#install missing ones
if(length(new.packages)) install.packages(new.packages, dependencies = TRUE)


library(shiny)
library(shinyFiles)
library(shinyTime)
library(shinyWidgets)
library(behavr)
library(data.table)
library(ggplot2)
library(damr) # input DAM data
library(zeitgebr) # periodogram computation
library(sleepr) # sleep analysis
library(ggetho) # behaviour visualisation
library(fs)
library(DT)
library(dplyr)
library(Hmisc)
library(shinyjs)
library(readr)
library(colourpicker)
library(lattice)
library(survival)
library(Formula)
library(stringr)
library(DescTools)
library(graphics)
library(doBy)
library(zoo)
library(tm)
library(base)
library(scales)
library(shinythemes)
library(xlsx)

shinyApp(
  
  
  
  ui <- navbarPage(id="pages",
                   theme = shinytheme("spacelab"),
                   
                   shinyjs::useShinyjs(),
                   
  
  # Import and select data to analyse                   
                                    
                   tabPanel(title = "Data selection", 
                      
                            tags$head(tags$style(".navbar {font-size:22px; font-weight:bold; font-family: Arial}
                                                 .nav-tabs {font-size:16px}")),

                              h1("Rtivity", align = "center", style = "font-family: Cambria; font-size: 70px;
                           font-weight:bold "),
                           #
                            h3("A versatile software for the automated analysis of animal activity and sleep patterns", align = "center", style = "font-family: Cambria; font-size: 35px;
                           font-weight:bold;margin-bottom: 80px"),
                            
                            
                            source("Data_selection_ui.R", local=TRUE)[1]
                   ),
                   
  # Represent activity and sleep in a time-continuous manner                
   
                   tabPanel("Periodic representations",
                            source("Periodic_representations_ui.R", local=TRUE)[1]),
                   
  # Represent and calculate activity and sleep statistics
  
                   tabPanel("Activity and sleep statistics",
                            source("Activity_and_sleep_ui.R", local=TRUE)[1]),
  
  # Represent and calculate activity and sleep statistics
                   
                   tabPanel("Bouts statistics",
                            source("Bouts_ui.R", local=TRUE)[1]
                   )
  ),
  
  
  server <- function(input, output,session){
    
    ### Global functions ###
    
    #Delete conditions function
    
    # session$onSessionEnded(function() {
    #   stopApp()
    #   q("no")
    # })

    deleteButtonColumn <- function(df, id, ...) {
      # function to create one action button as string
      f <- function(i) {
        as.character(
          actionButton(
            # The id prefix with index
            paste(id, i, sep="_"),
            label = NULL,
            icon = icon('trash'),
            onclick = 'Shiny.setInputValue(\"deletePressed\", this.id, {priority: "event"})'))
      }
      
      if(is.null(df)==FALSE){
        deleteCol <- unlist(lapply(seq_len(nrow(df)), f))
        
        data.frame(df,deleteCol)
      }
    }
    
    # Extract the number of the row to delete
    parseDeleteEvent <- function(idstr) {
      res <- as.integer(sub(".*_([0-9]+)", "\\1", idstr))
      if (! is.na(res)) res
    }
    
    #Set data
    source("Data_selection_server.R", local = TRUE)
    
    #Time-continuous graphs
    source("Periodic_representations_server.R", local = TRUE)

    #Activity and sleep statistical graphs and parameters
    source("Activity_and_sleep_server.R", local = TRUE)

    #Bouts statistical graphs and parameters
    source("Bouts_server.R", local = TRUE)
  })

